{% set name = "globus-compute-endpoint" %}
{% set version = "3.16.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e0ca58d98600acf1a5c88779e2125fe4aa2b076602aed44b8204e28be1df4695

build:
  entry_points:
    - globus-compute-endpoint=globus_compute_endpoint.cli:cli_run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - click-option-group >=0.5.6,<1
    - python >={{ python_min }}
    - requests >=2.31.0,<3
    - globus-sdk
    - globus-compute-sdk ==3.16.1
    - globus-identity-mapping ==0.4.0
    - texttable >=1.6.4,<2
    - psutil <6
    - python-daemon >=2,<3
    - click >=8,<8.2.0
    - click-option-group >=0.5.6,<1
    - pyzmq >=22.0.0,!=22.3.0,<=26.1.0
    - parsl ==2025.9.15
    - pika >=1.2.0
    - pyprctl <0.2.0
    - setproctitle >=1.3.2,<1.4
    - pyyaml >=6.0,<7.0
    - jinja2 >=3.1.6,<3.2
    - jsonschema >=4.21,<5
    - cachetools >=5.3.1
    - types-cachetools >=5.3.0.6

test:
  imports:
    - globus_compute_endpoint
  commands:
    - pip check
    - globus-compute-endpoint --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/globus/globus-compute
  summary: 'Globus Compute: High Performance Function Serving for Science'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
    - conda-forge/globus-compute-sdk
