{% set name = "globus-compute-endpoint" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/globus-compute-endpoint-{{ version }}.tar.gz
  sha256: fb06d9aa7d6d8daa4ddb9c2bdce2eee6caf7744d7dd9e6db6dbb6e8cdd41a316

build:
  entry_points:
    - globus-compute-endpoint=globus_compute_endpoint.cli:cli_run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    # Package officially only supports Linux, because uses pwd module
    # Theoretically pwd module works for all unix platforms
    - __unix
    - python >=3.7
    # https://github.com/funcx-faas/funcX/blob/main/compute_endpoint/setup.py
    - requests >=2.20.0,<3
    - globus-sdk
    - globus-compute-sdk =={{ version }}
    - globus-compute-common ==0.3.0
    - texttable >=1.6.4,<2
    - psutil <6
    - python-daemon >=2,<3
    - click >=8,<9
    - pyzmq >=22.0.0,!=22.3.0,<=23.2.0
    - parsl =2023.7.3
    - pika >=1.2.0
    - pyprctl <0.2.0
    - setproctitle >=1.3.2,<1.4
    - pyyaml >=6.0,<7.0
    - jinja2 >=3.1.2,<3.2
    - jsonschema >=4.19.0,<4.20
    - cachetools
    - globus-identity-mapping
    - types-cachetools

test:
  imports:
    - globus_compute_endpoint
  commands:
    - pip check
    - globus-compute-endpoint --help
  requires:
    - pip

about:
  home: https://github.com/funcx-faas/funcx
  summary: 'Globus Compute: High Performance Function Serving for Science'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carterbox
    - conda-forge/funcx
