schema_version: 1

context:
  name: globus-compute-endpoint
  version: 4.13.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: cc726f5670130e3020b34ed2961f8cfa206535e220f9a64f431115670f0451b2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - globus-compute-endpoint=globus_compute_endpoint.cli:cli_run

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - click-option-group >=0.5.6,<1
    - python >=${{ python_min }}
    - requests >=2.31.0,<3
    - globus-sdk
    - globus-compute-sdk ==4.13.0
    - globus-identity-mapping ==0.5.0
    - texttable >=1.6.4,<2
    - psutil <6
    - python-daemon >=2,<3
    - click >=8,<8.2.0
    - click-option-group >=0.5.6,<1
    - pyzmq >=22.0.0,!=22.3.0,<=26.1.0
    - parsl ==2026.4.20
    - pika >=1.2,<1.4
    - pyprctl <0.2.0
    - setproctitle >=1.3.2,<1.4
    - pyyaml >=6.0,<7.0
    - jinja2 >=3.1.6,<3.2
    - jsonschema >=4.21,<5
    - cachetools >=5.3.1
    - types-cachetools >=5.3.0.6
tests:
  - python:
      imports:
        - globus_compute_endpoint
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - globus-compute-endpoint --help

about:
  summary: 'Globus Compute: High Performance Function Serving for Science'
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/globus/globus-compute

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
    - conda-forge/globus-compute-sdk
